import type { Metadata } from "next";
import { DM_Serif_Text } from "next/font/google";
import "./globals.css";

const dmSerifText = DM_Serif_Text({
  variable: "--font-dm-serif-text",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSerifText.variable} antialiased`}>
        <div className="flex p-4 pt-12 justify-center bg-slate-200 min-h-dvh">
          <div className="bg-white shadow-md shadow-slate-300/30 p-6 rounded-xl h-fit w-full max-w-xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
